VPN_Service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("vpn/", include("vpn.urls", namespace="vpn")),
    path("", include("vpn.urls", namespace="vpn")),
    path("accounts/", include("django.contrib.auth.urls")),

    path("__debug__/", include("debug_toolbar.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vpn/urls.py
from django.urls import path

from .views import (
    index,
    SiteListView,
    SiteDetailView, RegisterView, SiteCreateView, SiteUpdateView, SiteDeleteView, ProfileDetailView, ProfileUpdateView,
)

urlpatterns = [
    path("", index, name="index"),
    path("profile/<int:pk>/", ProfileDetailView.as_view(), name="profile-detail"),
    path("profile/<int:pk>/update/", ProfileUpdateView.as_view(), name="profile-update"),
    path("register/", RegisterView.as_view(), name="register"),
    path("sites/", SiteListView.as_view(), name="site-list"),
    path(
        "sites/create/",
        SiteCreateView.as_view(),
        name="site-create",
    ),
    path(
        "sites/<int:pk>/update/",
        SiteUpdateView.as_view(),
        name="site-update",
    ),
    path(
        "sites/<int:pk>/delete/",
        SiteDeleteView.as_view(),
        name="site-delete",
    ),
    path("sites/<int:pk>/", SiteDetailView.as_view(), name="site-detail"),
]

app_name = "vpn"

vpn/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class User(AbstractUser):

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("vpn:user-detail", args=[str(self.id)])


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveIntegerField(blank=True)
    nick_name = models.CharField(max_length=63, unique=True, blank=False)
    nation = models.CharField(max_length=255)
    info = models.TextField(blank=False)

    def __str__(self):
        return f"{self.nick_name}"

    def get_absolute_url(self):
        return reverse("vpn:profile-detail", args=[str(self.id)])


class Site(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    site_name = models.CharField(max_length=255)
    site_url = models.URLField()

    def __str__(self):
        return f"{self.site_name}"

    def get_absolute_url(self):
        return reverse("vpn:site-detail", args=[str(self.id)])


class Statistics(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    page_views = models.PositiveIntegerField()
    data_sent = models.PositiveIntegerField()
    data_received = models.PositiveIntegerField()

    def __str__(self):
        return f"Data received: {self.data_received}, data sent: {self.data_sent}, page views: {self.page_views}"


class InternalRoute(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    site_name = models.CharField(max_length=255)
    internal_route = models.CharField(max_length=255)

    def get_absolute_url(self):
        return f"/{self.user.username}/{self.site_name}/{self.internal_route}"

vpn/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

from vpn.models import Site, Profile


class RegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name')


class SiteForm(forms.ModelForm):

    class Meta:
        model = Site
        fields = ("site_name", "site_url")
        exclude = ['user']


class SiteSearchForm(forms.Form):
    site_name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by site name"})
    )


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = "__all__"

vpn/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import  FormView

from .forms import RegisterForm, SiteForm, SiteSearchForm, ProfileForm
from .models import User, Site, Profile


@login_required
def index(request):
    """View function for the home page of the site."""

    num_users = User.objects.count()
    num_sites = Site.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_users": num_users,
        "num_sites": num_sites,
        "num_visits": num_visits + 1,
    }

    return render(request, "vpn/index.html", context=context)


class SiteListView(LoginRequiredMixin, generic.ListView):
    model = Site
    template_name = 'vpn/site_list.html'
    context_object_name = 'site_list'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(SiteListView, self).get_context_data(**kwargs)

        site_name = self.request.GET.get("site_name", "")

        context["search_form"] = SiteSearchForm(
            initial={
                "site_name": site_name
            }
        )

        return context

    def get_queryset(self):
        queryset = Site.objects.filter(user=self.request.user)
        form = SiteSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                site_name__icontains=form.cleaned_data["site_name"],
            )

        return queryset


class SiteCreateView(LoginRequiredMixin, generic.CreateView):
    model = Site
    form_class = SiteForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class SiteDetailView(LoginRequiredMixin, generic.DetailView):
    model = Site


class SiteUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Site
    form_class = SiteForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class SiteDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Site
    success_url = reverse_lazy("vpn:site-list")
    template_name = "vpn/site_confirm_delete.html"

    def get_queryset(self):
        return Site.objects.filter(user=self.request.user)


# class UserDetailView(LoginRequiredMixin, generic.DetailView):
#     model = User
#     queryset = User.objects.all()


# @login_required
# def profile_view(request):
#     return render(request, "vpn/profile.html")

class ProfileDetailView(LoginRequiredMixin, generic.DetailView):
    model = Profile
    template_name = 'vpn/profile.html'


class ProfileUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Profile
    form_class = ProfileForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class RegisterView(FormView):
    form_class = RegisterForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy("vpn:profile-detail")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>VPN Service</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item"><a href="{% url 'vpn:profile-detail' pk=user.id %}">User: {{ user.username }}</a></li>
    <li class="list-group-item"><a href="{% url 'logout' %}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login' %}">Login</a></li>
  {% endif %}

  <br>
  {% if user.is_authenticated %}
  <li class="list-group-item"><a href="{% url "vpn:profile-detail" pk=user.id %}">Personal Cabinet</a></li>
  <li class="list-group-item"><a href="{% url "vpn:site-list" %}">Sites</a></li>
{#  <li class="list-group-item"><a href="{% url "taxi:car-list" %}">Cars</a></li>#}
{#  <li class="list-group-item"><a href="{% url "taxi:driver-list" %}">Drivers</a></li>#}
  {% endif %}
</ul>

templates/vpn/index.html
{% extends "base.html" %}

{% block content %}
  <h1>VPN Service Home</h1>
  <p>Welcome to VPN Service Ever!</p>
  <h2>Dynamic content</h2>
  <p>VPN service has the following record counts:</p>
  <ul>
    <li><strong>Sites:</strong> {{ num_sites }}</li>
    <li><strong>Users:</strong> {{ num_users }}</li>
  </ul>
  <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}</p>
{% endblock %}

templates/vpn/profile.html
{% extends "base.html" %}

{% block content %}
  <div class="container mx-auto mt-8">
    <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
      <h1 class="text-4xl font-bold mb-4">{{ profile.nick_name }} Profile</h1>
    <a style="float: right" class="btn btn-primary" href="{% url 'vpn:profile-update' pk=user.id%}">Update info</a>
      <h2 class="text-lg mb-4">{% if user.preferences %}({{ user.preferences }}){% endif %}</h2>
      <hr class="mb-4">

      <div class="mb-4">
        <h3 class="text-xl font-bold mb-2">User Information</h3>
        <dl class="grid grid-cols-2 gap-4">
          <dt class="text-gray-500">User:</dt>
          <dd>{{ user.first_name }} {{ user.last_name }}</dd>

          <dt class="text-gray-500">Email:</dt>
          <dd>{{ user.email }}</dd>

          <dt class="text-gray-500">Age:</dt>
          <dd>{{ profile.age }}</dd>
        </dl>
      </div>

      <div>
        <h3 class="text-xl font-bold mb-2">Additional Information</h3>
        <p>{{ profile.info }}</p>
      </div>

      <div class="mt-6">
        <a href="{% url 'vpn:profile-update' pk=user.id  %}" class="bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-700">
          Edit Profile
        </a>
      </div>
    </div>
  </div>
{% endblock %}

templates/vpn/profile_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update"}} User</h1>

  <form action="", method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}

    <input class="btm btn-primary" type="submit", value="Submit">
  </form>
{% endblock %}

templates/vpn/profile_update.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>Edit Profile</h1>
    <form method="post" action="">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Save Changes" class="btn btn-primary">
    </form>
{% endblock %}

templates/vpn/site_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete a Site</h1>
  <p>Are you sure that you want to delete site: {{ site }}</p>

  <form action="", method="POST">
  {% csrf_token %}
    <input type="submit", value="Yes, delete" class="btn btn-danger"/>
  </form>


{% endblock %}

templates/vpn/site_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Title: {{ site.site_name }}
  <a style="float: right" class="btn btn-secondary" href="{% url 'vpn:site-update' pk=site.id %}">Edit</a>
  </h1>
  <p><strong>Site Name: {{ site.site_name }}</strong></p>
  <p><strong>Format: {{ site.site_url }}</strong></p>

{% endblock %}

templates/vpn/site_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create"}} a Site</h1>

  <form action="", method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}

    <input class="btm btn-primary" type="submit", value="Submit">
  </form>
{% endblock %}

templates/vpn/site_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Sites List
  <a style="float: right" class="btn btn-primary" href="{% url 'vpn:site-create' %}">Add New Site +</a>
  </h1>
  <hr>
  <form action="" method="get" class="form-inline">
  {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="🔎">
  </form>
  <hr>
  {% if site_list %}
    <table class="table">
    <tr>
      <th>Site name</th>
      <th>Site link</th>
      <th>Go to site</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>

    {% for site in site_list %}
    <tr>
      <td>
        {{site.site_name}}
      </td>
      <td>
        {{ site.site_url }}
      </td>
      <td>
        <a class="btn btn-primary" href="{{site.get_absolute_url}}">Go to site!</a>
      </td>
        <td>
            <a href="{% url 'vpn:site-update' pk=site.id %}">update</a>
        </td>
      <td>
            <a class="btn btn-danger" href="{% url 'vpn:site-delete' pk=site.id %}">delete</a>
      </td>
    </tr>
    {% endfor %}
    </table>
    {% else %}
      <p>No sites, motherfucker</p>
    {% endif %}

{% endblock %}

templates/vpn/user_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Name: {{ author.first_name }} {{ author.last_name }}</h1>
  <h2>{% if author.pseudonym %}({{ author.pseudonym }}){% endif %}</h2>
  <hr>
  <p><strong>Username: {{ author.username }}</strong></p>
  <p><strong>Email: {{ author.email }}</strong></p>
  <p><strong>Is staff: {{ author.is_staff }}</strong></p>
  <hr>
{% endblock %}